name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - name: checking out the code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
      - name: Install dependencies
        run: go install honnef.co/go/tools/cmd/staticcheck@latest
      - name: Run go vet for linting
        run: go vet ./...
      - name: go staticcheck for code analyse
        run: staticcheck ./...

#          - name: go test
#         run: go test ./... -v      //I will addd the test later
#            env:
#              CI: true

  build_and_release:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@master
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
         go-version: '1.22'
      - name: build
        run: go build .
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
         node-version: "lts/*"
      - name: Install dependencies
        run: npm install
      - name: Release
        run: cp .github/.releaserc.json .
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          DEBUG: semantic-release:*

        run: npx semantic-release
